version: '3.8'
services:
  web:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    depends_on:
      - db
    ports:
      - "8080:8080"
  db:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: 123456
      MYSQL_DATABASE: tally
      MYSQL_USER: tally
      MYSQL_PASSWORD: tally
    ports:
    - "3306:3306"
    volumes:
      - "../sql/:/docker-entrypoint-initdb.d/"
